### ISSUE TITLE
CPython changelog

### ISSUE THREAD

**Issue by m-aciek** [rffontenelle/python-docs-tx-translations#101]
With regard to the [discussion on Discord](https://discord.com/channels/935215565872693329/1305843741700915271/1309196481298825297) and in [translations dashboard PR](https://github.com/m-aciek/pydocs-translation-dashboard/pull/6#issuecomment-2491031268), just want to leave a trace here that we are not currently synchronising the changelog resource, [which is built by blurb](https://github.com/python/cpython/blob/a880358af03d9cab37f7db04385c5a97051b03b6/Doc/Makefile#L64) in the original CPython documentation. We may want to decide at some point in the future what to do about it. Either to include it or ignore it (ignoring is now a status quo for Transifex translations).

cc @Dumeng, @BlueGlassBlock, @zhsj, @egeakman

**Comment by rffontenelle** [comment]
It would be good if all of you could express your opinion on this. If no objection is raised, I can change the workflow to extract changelog strings as well.

**Comment by Dumeng** [comment]
LGTM

**Comment by egeakman** [comment]
I don't know if all the translation teams currently have the capacity to add a big chunk of content to their *to-translate* list. On the other hand, any team that wants to ignore it can keep ignoring it, so I don't see a problem moving forward with it.

**Comment by rffontenelle** [comment]
Pull request is ready for enabling translation of whatsnew/changelog, but I plan to skip this Friday's update to give more time.
